# Makefile generated by imake - do not edit!
# $XConsortium: imake.c,v 1.65 91/07/25 17:50:17 rws Exp $
#
# The cpp used on this machine replaces all newlines and multiple tabs and
# spaces in a macro expansion with a single space.  Imake tries to compensate
# for this, but is not always successful.
#

# -------------------------------------------------------------------------
# Makefile generated from "Imake.tmpl" and <Imakefile>
# $XConsortium: Imake.tmpl,v 1.139 91/09/16 08:52:48 rws Exp $
#
# Platform-specific parameters may be set in the appropriate <vendor>.cf
# configuration files.  Site-specific parameters should be set in the file
# site.def.  Full rebuilds are recommended if any parameters are changed.
#
# If your C preprocessor does not define any unique symbols, you will need
# to set BOOTSTRAPCFLAGS when rebuilding imake (usually when doing
# "make World" the first time).
#

# -------------------------------------------------------------------------
# site-specific configuration parameters that need to come before
# the platform-specific parameters - edit site.def to change

# site:  $XConsortium: site.def,v 1.2 91/07/30 20:26:44 rws Exp $

# -------------------------------------------------------------------------
# platform-specific configuration parameters - edit sun.cf to change

# platform:  $XConsortium: sun.cf,v 1.72.1.1 92/03/18 13:13:37 rws Exp $

# operating system:  SunOS 4.1.1

# $XConsortium: sunLib.rules,v 1.7 91/12/20 11:19:47 rws Exp $

# -------------------------------------------------------------------------
# site-specific configuration parameters that go after
# the platform-specific parameters - edit site.def to change

# site:  $XConsortium: site.def,v 1.2 91/07/30 20:26:44 rws Exp $

            SHELL = /bin/sh

              TOP = .
      CURRENT_DIR = .

               AR = ar clq
  BOOTSTRAPCFLAGS =
               CC = cc
               AS = as

         COMPRESS = compress
              CPP = /lib/cpp $(STD_CPP_DEFINES)
    PREPROCESSCMD = cc -E $(STD_CPP_DEFINES)
          INSTALL = install
               LD = ld
             LINT = lint
      LINTLIBFLAG = -C
         LINTOPTS = -axz
               LN = ln -s
             MAKE = make
               MV = mv
               CP = cp

           RANLIB = ranlib
  RANLIBINSTFLAGS =

               RM = rm -f
            TROFF = psroff
         MSMACROS = -ms
              TBL = tbl
              EQN = eqn
     STD_INCLUDES =
  STD_CPP_DEFINES =
      STD_DEFINES =
 EXTRA_LOAD_FLAGS =
  EXTRA_LIBRARIES =
             TAGS = ctags

    SHAREDCODEDEF = -DSHAREDCODE
         SHLIBDEF = -DSUNSHLIB

    PROTO_DEFINES =

     INSTPGMFLAGS =

     INSTBINFLAGS = -m 0755
     INSTUIDFLAGS = -m 4755
     INSTLIBFLAGS = -m 0644
     INSTINCFLAGS = -m 0444
     INSTMANFLAGS = -m 0444
     INSTDATFLAGS = -m 0444
    INSTKMEMFLAGS = -g kmem -m 2755

      PROJECTROOT = /usr/staff

     TOP_INCLUDES = -I$(INCROOT)

      CDEBUGFLAGS = -O
        CCOPTIONS = -pipe

      ALLINCLUDES = $(INCLUDES) $(EXTRA_INCLUDES) $(TOP_INCLUDES) $(STD_INCLUDES)
       ALLDEFINES = $(ALLINCLUDES) $(STD_DEFINES) $(EXTRA_DEFINES) $(PROTO_DEFINES) $(DEFINES)
           CFLAGS = $(CDEBUGFLAGS) $(CCOPTIONS) $(ALLDEFINES)
        LINTFLAGS = $(LINTOPTS) -DLINT $(ALLDEFINES)

           LDLIBS = $(SYS_LIBRARIES) $(EXTRA_LIBRARIES)

        LDOPTIONS = $(CDEBUGFLAGS) $(CCOPTIONS) $(LOCAL_LDFLAGS) -L$(USRLIBDIR)

   LDCOMBINEFLAGS = -X -r
      DEPENDFLAGS =

        MACROFILE = sun.cf
           RM_CMD = $(RM) *.CKP *.ln *.BAK *.bak *.o core errs ,* *~ *.a .emacs_* tags TAGS make.log MakeOut

    IMAKE_DEFINES =

         IRULESRC = $(CONFIGDIR)
        IMAKE_CMD = $(IMAKE) -DUseInstalled -I$(IRULESRC) $(IMAKE_DEFINES)

     ICONFIGFILES = $(IRULESRC)/Imake.tmpl $(IRULESRC)/Imake.rules \
			$(IRULESRC)/Project.tmpl $(IRULESRC)/site.def \
			$(IRULESRC)/$(MACROFILE) $(EXTRA_ICONFIGFILES)

# -------------------------------------------------------------------------
# X Window System Build Parameters
# $XConsortium: Project.tmpl,v 1.138 91/09/10 09:02:12 rws Exp $

# -------------------------------------------------------------------------
# X Window System make variables; this need to be coordinated with rules

          PATHSEP = /
        USRLIBDIR = /usr/staff/lib
           BINDIR = /usr/staff/bin
          INCROOT = /usr/staff/include
     BUILDINCROOT = $(TOP)
      BUILDINCDIR = $(BUILDINCROOT)/X11
      BUILDINCTOP = ..
           INCDIR = $(INCROOT)/X11
           ADMDIR = /usr/adm
           LIBDIR = $(USRLIBDIR)/X11
        CONFIGDIR = $(LIBDIR)/config
       LINTLIBDIR = $(USRLIBDIR)/lint

          FONTDIR = $(LIBDIR)/fonts
         XINITDIR = $(LIBDIR)/xinit
           XDMDIR = $(LIBDIR)/xdm
           TWMDIR = $(LIBDIR)/twm
          MANPATH = /usr/staff/man
    MANSOURCEPATH = $(MANPATH)/man
        MANSUFFIX = 1
     LIBMANSUFFIX = 3
           MANDIR = $(MANSOURCEPATH)$(MANSUFFIX)
        LIBMANDIR = $(MANSOURCEPATH)$(LIBMANSUFFIX)
           NLSDIR = $(LIBDIR)/nls
        PEXAPIDIR = $(LIBDIR)/PEX
      XAPPLOADDIR = $(LIBDIR)/app-defaults
       FONTCFLAGS = -t

     INSTAPPFLAGS = $(INSTDATFLAGS)

            IMAKE = imake
           DEPEND = makedepend
              RGB = rgb

            FONTC = bdftopcf

        MKFONTDIR = mkfontdir
        MKDIRHIER = /bin/sh $(BINDIR)/mkdirhier

        CONFIGSRC = $(TOP)/config
       DOCUTILSRC = $(TOP)/doc/util
        CLIENTSRC = $(TOP)/clients
          DEMOSRC = $(TOP)/demos
           LIBSRC = $(TOP)/lib
          FONTSRC = $(TOP)/fonts
       INCLUDESRC = $(TOP)/X11
        SERVERSRC = $(TOP)/server
          UTILSRC = $(TOP)/util
        SCRIPTSRC = $(UTILSRC)/scripts
       EXAMPLESRC = $(TOP)/examples
       CONTRIBSRC = $(TOP)/../contrib
           DOCSRC = $(TOP)/doc
           RGBSRC = $(TOP)/rgb
        DEPENDSRC = $(UTILSRC)/makedepend
         IMAKESRC = $(CONFIGSRC)
         XAUTHSRC = $(LIBSRC)/Xau
          XLIBSRC = $(LIBSRC)/X
           XMUSRC = $(LIBSRC)/Xmu
       TOOLKITSRC = $(LIBSRC)/Xt
       AWIDGETSRC = $(LIBSRC)/Xaw
       OLDXLIBSRC = $(LIBSRC)/oldX
      XDMCPLIBSRC = $(LIBSRC)/Xdmcp
      BDFTOSNFSRC = $(FONTSRC)/bdftosnf
      BDFTOSNFSRC = $(FONTSRC)/clients/bdftosnf
      BDFTOPCFSRC = $(FONTSRC)/clients/bdftopcf
     MKFONTDIRSRC = $(FONTSRC)/clients/mkfontdir
         FSLIBSRC = $(FONTSRC)/lib/fs
    FONTSERVERSRC = $(FONTSRC)/server
     EXTENSIONSRC = $(TOP)/extensions
         XILIBSRC = $(EXTENSIONSRC)/lib/xinput
      PHIGSLIBSRC = $(EXTENSIONSRC)/lib/PEX

# $XConsortium: sunLib.tmpl,v 1.14.1.1 92/03/17 14:58:46 rws Exp $

SHLIBLDFLAGS = -assert pure-text
PICFLAGS = -pic

  DEPEXTENSIONLIB =
     EXTENSIONLIB = -lXext

          DEPXLIB = $(DEPEXTENSIONLIB)
             XLIB = $(EXTENSIONLIB) -lX11

        DEPXMULIB = $(USRLIBDIR)/libXmu.sa.$(SOXMUREV)
       XMULIBONLY = -lXmu
           XMULIB = -lXmu

       DEPOLDXLIB =
          OLDXLIB = -loldX

      DEPXTOOLLIB = $(USRLIBDIR)/libXt.sa.$(SOXTREV)
         XTOOLLIB = -lXt

        DEPXAWLIB = $(USRLIBDIR)/libXaw.sa.$(SOXAWREV)
           XAWLIB = -lXaw

        DEPXILIB =
           XILIB = -lXi

        SOXLIBREV = 4.10
          SOXTREV = 4.10
         SOXAWREV = 5.0
        SOOLDXREV = 4.10
         SOXMUREV = 4.10
        SOXEXTREV = 4.10
      SOXINPUTREV = 4.10

      DEPXAUTHLIB = $(USRLIBDIR)/libXau.a
         XAUTHLIB =  -lXau
      DEPXDMCPLIB = $(USRLIBDIR)/libXdmcp.a
         XDMCPLIB =  -lXdmcp

        DEPPHIGSLIB = $(USRLIBDIR)/libphigs.a
           PHIGSLIB =  -lphigs

       DEPXBSDLIB = $(USRLIBDIR)/libXbsd.a
          XBSDLIB =  -lXbsd

 LINTEXTENSIONLIB = $(LINTLIBDIR)/llib-lXext.ln
         LINTXLIB = $(LINTLIBDIR)/llib-lX11.ln
          LINTXMU = $(LINTLIBDIR)/llib-lXmu.ln
        LINTXTOOL = $(LINTLIBDIR)/llib-lXt.ln
          LINTXAW = $(LINTLIBDIR)/llib-lXaw.ln
           LINTXI = $(LINTLIBDIR)/llib-lXi.ln
        LINTPHIGS = $(LINTLIBDIR)/llib-lphigs.ln

          DEPLIBS = $(DEPXAWLIB) $(DEPXMULIB) $(DEPXTOOLLIB) $(DEPXLIB)

         DEPLIBS1 = $(DEPLIBS)
         DEPLIBS2 = $(DEPLIBS)
         DEPLIBS3 = $(DEPLIBS)

# -------------------------------------------------------------------------
# Imake rules for building libraries, programs, scripts, and data files
# rules:  $XConsortium: Imake.rules,v 1.123 91/09/16 20:12:16 rws Exp $

# -------------------------------------------------------------------------
# start of Imakefile

#
# Imakefile for xse - an interface to XSendEvent()
#
# George Ferguson, ferguson@cs.rochester.edu, 1 Jun 1990.
#
# Version 1.6 - 5 Jan 1992
# Version 2.0 - 31 Jan 1992
# Version 2.1 -  4 Apr 1993
#

# Uncomment to enable debugging
#CDEBUGFLAGS = -g

# Where is the app-defaults to C converter?
# Only needed if you change the app-defaults file Xse.ad and want the
# changes compiled into the program.
# If your ad2c came from this xse distribution, then use the following
# target, otherwise change it to reflect where you put ad2c.
AD2C = Ad2c/ad2c.script

# If you don't have strcasecmp() and strncasecmp(), adjust the
# following definitions:

# If you don't have strtol(), adjust the following definitions:

#########################################################################
# Nothing to change below here...

LOCAL_LIBRARIES =	$(XAWLIB) $(XMULIB) $(XTOOLLIB) $(XLIB)

SRCS = xse.c parse.c window.c translate.c $(STRCASECMPC) $(STRTOLC)
OBJS = xse.o parse.o window.o translate.o $(STRCASECMPO) $(STRTOLO)

 PROGRAM = xse

all:: xse

xse: $(OBJS) $(DEPLIBS)
	$(RM) $@
	$(CC) -o $@ $(OBJS) $(LDOPTIONS) $(LOCAL_LIBRARIES) $(LDLIBS) $(EXTRA_LOAD_FLAGS)

saber_xse:: $(SRCS)
	# load $(ALLDEFINES) $(SRCS) $(LOCAL_LIBRARIES) $(SYS_LIBRARIES) $(EXTRA_LIBRARIES)

osaber_xse:: $(OBJS)
	# load $(ALLDEFINES) $(OBJS) $(LOCAL_LIBRARIES) $(SYS_LIBRARIES) $(EXTRA_LIBRARIES)

install:: xse
	@if [ -d $(DESTDIR)$(BINDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); fi
	$(INSTALL) -c $(INSTPGMFLAGS)  xse $(DESTDIR)$(BINDIR)

install.man:: xse.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(INSTALL) -c $(INSTMANFLAGS) xse.man $(DESTDIR)$(MANDIR)/xse.$(MANSUFFIX)

depend::
	$(DEPEND) $(DEPENDFLAGS) -s "# DO NOT DELETE" -- $(ALLDEFINES) -- $(SRCS)

lint:
	$(LINT) $(LINTFLAGS) $(SRCS) $(LINTLIBS)
lint1:
	$(LINT) $(LINTFLAGS) $(FILE) $(LINTLIBS)

clean::
	$(RM) $(PROGRAM)

#
# C code for fallback resources
#
Xse.ad.h: Xse.ad
	$(AD2C) Xse.ad >Xse.ad.h

#
# What to do when there's nothing to do...
#
World:
	make Makefile
	make Makefiles
	make depend
	make clean
	make

# -------------------------------------------------------------------------
# common rules for all Makefiles - do not edit

emptyrule::

clean::
	$(RM_CMD) "#"*

Makefile::
	-@if [ -f Makefile ]; then set -x; \
	$(RM) Makefile.bak; $(MV) Makefile Makefile.bak; \
	else exit 0; fi
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)

tags::
	$(TAGS) -w *.[ch]
	$(TAGS) -xw *.[ch] > TAGS

saber:
	# load $(ALLDEFINES) $(SRCS)

osaber:
	# load $(ALLDEFINES) $(OBJS)

# -------------------------------------------------------------------------
# empty rules for directories that do not have SUBDIRS - do not edit

install::
	@echo "install in $(CURRENT_DIR) done"

install.man::
	@echo "install.man in $(CURRENT_DIR) done"

Makefiles::

includes::

# -------------------------------------------------------------------------
# dependencies generated by makedepend

# DO NOT DELETE

xse.o: /usr/include/stdio.h ctype.h /usr/staff/include/X11/Intrinsic.h
xse.o: /usr/staff/include/X11/Xlib.h /usr/include/sys/types.h
xse.o: /usr/include/sys/stdtypes.h /usr/include/sys/sysmacros.h
xse.o: /usr/staff/include/X11/X.h /usr/staff/include/X11/Xfuncproto.h
xse.o: /usr/staff/include/X11/Xosdefs.h /usr/include/stddef.h
xse.o: /usr/staff/include/X11/Xutil.h /usr/staff/include/X11/Xresource.h
xse.o: /usr/include/string.h /usr/staff/include/X11/Core.h
xse.o: /usr/staff/include/X11/Composite.h /usr/staff/include/X11/Constraint.h
xse.o: /usr/staff/include/X11/Object.h /usr/staff/include/X11/RectObj.h
xse.o: /usr/staff/include/X11/StringDefs.h /usr/staff/include/X11/Shell.h
xse.o: /usr/staff/include/X11/Xaw/Form.h /usr/staff/include/X11/Xaw/Command.h
xse.o: /usr/staff/include/X11/Xaw/Label.h /usr/staff/include/X11/Xaw/Simple.h
xse.o: /usr/staff/include/X11/Xmu/Converters.h
xse.o: /usr/staff/include/X11/Xaw/Cardinals.h translate.h parse.h window.h
xse.o: patchlevel.h Xse.ad.h
parse.o: /usr/include/stdio.h /usr/staff/include/X11/Xlib.h
parse.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
parse.o: /usr/include/sys/sysmacros.h /usr/staff/include/X11/X.h
parse.o: /usr/staff/include/X11/Xfuncproto.h /usr/staff/include/X11/Xosdefs.h
parse.o: /usr/include/stddef.h /usr/staff/include/X11/keysym.h
parse.o: /usr/staff/include/X11/keysymdef.h /usr/staff/include/X11/Xproto.h
parse.o: /usr/staff/include/X11/Xmd.h /usr/staff/include/X11/Xprotostr.h
parse.o: xse.h stringdefs.h config.h /usr/include/strings.h ctype.h window.h
window.o: /usr/include/stdio.h /usr/staff/include/X11/Xlib.h
window.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
window.o: /usr/include/sys/sysmacros.h /usr/staff/include/X11/X.h
window.o: /usr/staff/include/X11/Xfuncproto.h
window.o: /usr/staff/include/X11/Xosdefs.h /usr/include/stddef.h
window.o: /usr/staff/include/X11/Xatom.h /usr/staff/include/X11/Xmu/WinUtil.h
window.o: /usr/staff/include/X11/Xutil.h /usr/staff/include/X11/cursorfont.h
translate.o: /usr/staff/include/X11/Intrinsic.h /usr/staff/include/X11/Xlib.h
translate.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
translate.o: /usr/include/sys/sysmacros.h /usr/staff/include/X11/X.h
translate.o: /usr/staff/include/X11/Xfuncproto.h
translate.o: /usr/staff/include/X11/Xosdefs.h /usr/include/stddef.h
translate.o: /usr/staff/include/X11/Xutil.h
translate.o: /usr/staff/include/X11/Xresource.h /usr/include/string.h
translate.o: /usr/staff/include/X11/Core.h /usr/staff/include/X11/Composite.h
translate.o: /usr/staff/include/X11/Constraint.h
translate.o: /usr/staff/include/X11/Object.h /usr/staff/include/X11/RectObj.h
translate.o: /usr/staff/include/X11/StringDefs.h
translate.o: /usr/staff/include/X11/Xaw/Command.h
translate.o: /usr/staff/include/X11/Xaw/Label.h
translate.o: /usr/staff/include/X11/Xaw/Simple.h
translate.o: /usr/staff/include/X11/Xmu/Converters.h
translate.o: /usr/staff/include/X11/Xaw/Grip.h
translate.o: /usr/staff/include/X11/Xaw/List.h
translate.o: /usr/staff/include/X11/Xaw/Scrollbar.h
translate.o: /usr/staff/include/X11/Xaw/StripChart.h
translate.o: /usr/staff/include/X11/Xaw/Toggle.h
translate.o: /usr/staff/include/X11/Xaw/SimpleMenu.h
translate.o: /usr/staff/include/X11/Shell.h
translate.o: /usr/staff/include/X11/Xaw/SmeBSB.h
translate.o: /usr/staff/include/X11/Xaw/Sme.h
translate.o: /usr/staff/include/X11/Xaw/SmeLine.h
translate.o: /usr/staff/include/X11/Xaw/MenuButton.h
translate.o: /usr/staff/include/X11/Xaw/AsciiText.h
translate.o: /usr/staff/include/X11/Xaw/Text.h
translate.o: /usr/staff/include/X11/Xaw/TextSink.h
translate.o: /usr/staff/include/X11/Xaw/TextSrc.h
translate.o: /usr/staff/include/X11/Xaw/AsciiSrc.h
translate.o: /usr/staff/include/X11/Xaw/AsciiSink.h
translate.o: /usr/staff/include/X11/Xaw/Box.h
translate.o: /usr/staff/include/X11/Xaw/Dialog.h
translate.o: /usr/staff/include/X11/Xaw/Form.h
translate.o: /usr/staff/include/X11/Xaw/Paned.h
translate.o: /usr/staff/include/X11/Xaw/Viewport.h
translate.o: /usr/staff/include/X11/Xaw/Reports.h
